[2025-09-06T16:39:59.844+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T16:39:59.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_customers_to_postgres.print_success manual__2025-09-06T16:39:54.469471+00:00 [queued]>
[2025-09-06T16:39:59.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_customers_to_postgres.print_success manual__2025-09-06T16:39:54.469471+00:00 [queued]>
[2025-09-06T16:39:59.915+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T16:39:59.922+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): print_success> on 2025-09-06 16:39:54.469471+00:00
[2025-09-06T16:39:59.927+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4337) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-09-06T16:39:59.928+0000] {standard_task_runner.py:64} INFO - Started process 4338 to run task
[2025-09-06T16:39:59.927+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'load_customers_to_postgres', 'print_success', 'manual__2025-09-06T16:39:54.469471+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/load_customers_to_postgres.py', '--cfg-path', '/tmp/tmp0_ad3bil']
[2025-09-06T16:39:59.929+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask print_success
[2025-09-06T16:39:59.955+0000] {task_command.py:426} INFO - Running <TaskInstance: load_customers_to_postgres.print_success manual__2025-09-06T16:39:54.469471+00:00 [running]> on host dd8e0e853e24
[2025-09-06T16:39:59.999+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etl' AIRFLOW_CTX_DAG_ID='load_customers_to_postgres' AIRFLOW_CTX_TASK_ID='print_success' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T16:39:54.469471+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T16:39:54.469471+00:00'
[2025-09-06T16:40:00.000+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T16:40:00.001+0000] {logging_mixin.py:188} INFO - âœ… DAG run completed successfully: load_customers_to_postgres
[2025-09-06T16:40:00.001+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-06T16:40:00.001+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T16:40:00.006+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=load_customers_to_postgres, task_id=print_success, run_id=manual__2025-09-06T16:39:54.469471+00:00, execution_date=20250906T163954, start_date=20250906T163959, end_date=20250906T164000
[2025-09-06T16:40:00.027+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-09-06T16:40:00.037+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T16:40:00.038+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
